using System;
using System.IO;
using System.Text;
using AccessUtility.Models;

namespace AccessUtility.Exporters
{
    /// <summary>
    /// Feature 02: Generates ANSI SQL DDL/DML migration scripts from a SchemaDiffResult.
    /// Supports Access SQL, SQLite, PostgreSQL, and SQL Server dialect output.
    /// </summary>
    public static class MigrationScriptExporter
    {
        /// <summary>
        /// Generates a migration SQL script from a schema diff result.
        /// The script transforms the Target database schema to match the Source.
        /// </summary>
        /// <param name="diff">The schema diff result from SchemaComparer.</param>
        /// <param name="outputPath">Output .sql file path.</param>
        /// <param name="dialect">SQL dialect: "ansi" (default), "sqlite", "pgsql", "mssql".</param>
        /// <returns>The output file path.</returns>
        public static string GenerateMigrationScript(SchemaDiffResult diff, string outputPath, string dialect = "ansi")
        {
            var sb = new StringBuilder();

            // ── Header ──
            sb.AppendLine("-- ============================================================");
            sb.AppendLine("-- Migration Script: Generated by AccessUtility (.NET 10 AOT)");
            sb.AppendLine($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine($"-- Source: {Path.GetFileName(diff.SourcePath)}");
            sb.AppendLine($"-- Target: {Path.GetFileName(diff.TargetPath)}");
            sb.AppendLine($"-- Dialect: {dialect.ToUpper()}");
            sb.AppendLine("-- ============================================================");
            sb.AppendLine();

            if (!diff.HasDifferences)
            {
                sb.AppendLine("-- No schema differences detected. Databases are identical.");
                WriteTo(outputPath, sb);
                return outputPath;
            }

            // ── Summary ──
            sb.AppendLine($"-- Summary: {diff.AddedTables.Count} table(s) added, " +
                          $"{diff.RemovedTables.Count} table(s) removed, " +
                          $"{diff.ModifiedTables.Count} table(s) modified.");
            sb.AppendLine();

            // ── DROP removed tables ──
            if (diff.RemovedTables.Count > 0)
            {
                sb.AppendLine("-- ── Removed Tables ──");
                foreach (var table in diff.RemovedTables)
                {
                    sb.AppendLine($"DROP TABLE IF EXISTS {Quote(table.TableName, dialect)};");
                }
                sb.AppendLine();
            }

            // ── CREATE added tables ──
            if (diff.AddedTables.Count > 0)
            {
                sb.AppendLine("-- ── New Tables ──");
                foreach (var table in diff.AddedTables)
                {
                    sb.AppendLine($"CREATE TABLE {Quote(table.TableName, dialect)} (");
                    for (int i = 0; i < table.Columns.Count; i++)
                    {
                        var col = table.Columns[i];
                        string typeStr = MapDataType(col.DataType, col.Length, dialect);
                        string nullable = col.IsNullable ? "" : " NOT NULL";
                        string autoNum = col.IsAutoNumber ? PrimaryKeyAutoIncrement(dialect) : "";
                        string comma = i < table.Columns.Count - 1 ? "," : "";
                        sb.AppendLine($"    {Quote(col.Name, dialect)} {typeStr}{nullable}{autoNum}{comma}");
                    }
                    sb.AppendLine(");");
                    sb.AppendLine();
                }
            }

            // ── ALTER modified tables ──
            if (diff.ModifiedTables.Count > 0)
            {
                sb.AppendLine("-- ── Modified Tables ──");
                foreach (var table in diff.ModifiedTables)
                {
                    bool hasChanges = false;

                    // Added columns
                    foreach (var col in table.AddedColumns)
                    {
                        string typeStr = MapDataType(col.NewDataType, col.NewLength, dialect);
                        string nullable = col.IsNullable ? "" : " NOT NULL";
                        sb.AppendLine($"ALTER TABLE {Quote(table.TableName, dialect)} ADD COLUMN {Quote(col.ColumnName, dialect)} {typeStr}{nullable};");
                        hasChanges = true;
                    }

                    // Removed columns
                    foreach (var col in table.RemovedColumns)
                    {
                        if (dialect == "sqlite")
                        {
                            sb.AppendLine($"-- SQLite does not support DROP COLUMN prior to 3.35.0");
                            sb.AppendLine($"-- ALTER TABLE {Quote(table.TableName, dialect)} DROP COLUMN {Quote(col.ColumnName, dialect)};");
                        }
                        else
                        {
                            sb.AppendLine($"ALTER TABLE {Quote(table.TableName, dialect)} DROP COLUMN {Quote(col.ColumnName, dialect)};");
                        }
                        hasChanges = true;
                    }

                    // Modified columns
                    foreach (var col in table.ModifiedColumns)
                    {
                        string newType = MapDataType(col.NewDataType, col.NewLength, dialect);
                        string oldType = MapDataType(col.OldDataType, col.OldLength, dialect);

                        sb.AppendLine($"-- Column '{col.ColumnName}': {oldType} -> {newType}");

                        if (dialect == "pgsql")
                        {
                            sb.AppendLine($"ALTER TABLE {Quote(table.TableName, dialect)} ALTER COLUMN {Quote(col.ColumnName, dialect)} TYPE {newType};");
                        }
                        else if (dialect == "mssql")
                        {
                            sb.AppendLine($"ALTER TABLE {Quote(table.TableName, dialect)} ALTER COLUMN {Quote(col.ColumnName, dialect)} {newType};");
                        }
                        else
                        {
                            // ANSI / SQLite fallback: comment-only guidance
                            sb.AppendLine($"-- ALTER TABLE {Quote(table.TableName, dialect)} MODIFY COLUMN {Quote(col.ColumnName, dialect)} {newType};");
                            sb.AppendLine($"-- Note: Column type modification may require table recreation in Access/SQLite.");
                        }
                        hasChanges = true;
                    }

                    // Row count annotation
                    if (table.RowCountDifference != 0)
                    {
                        string direction = table.RowCountDifference > 0 ? "more" : "fewer";
                        sb.AppendLine($"-- Table '{table.TableName}': {Math.Abs(table.RowCountDifference)} {direction} row(s) in source ({table.SourceRowCount} vs {table.TargetRowCount}).");
                    }

                    if (hasChanges) sb.AppendLine();
                }
            }

            sb.AppendLine("-- End of migration script.");

            WriteTo(outputPath, sb);
            return outputPath;
        }

        /// <summary>
        /// Generates a human-readable diff report (not SQL) summarizing all differences.
        /// </summary>
        public static string GenerateDiffReport(SchemaDiffResult diff)
        {
            var sb = new StringBuilder();
            sb.AppendLine("╔══════════════════════════════════════════════════════════════╗");
            sb.AppendLine("║          Schema Diff Report — AccessUtility                 ║");
            sb.AppendLine("╚══════════════════════════════════════════════════════════════╝");
            sb.AppendLine();
            sb.AppendLine($"  Source : {diff.SourcePath}");
            sb.AppendLine($"  Target : {diff.TargetPath}");
            sb.AppendLine();

            if (!diff.HasDifferences)
            {
                sb.AppendLine("  ✅ No differences detected. Schemas are identical.");
                return sb.ToString();
            }

            sb.AppendLine($"  Added Tables   : {diff.AddedTables.Count}");
            sb.AppendLine($"  Removed Tables : {diff.RemovedTables.Count}");
            sb.AppendLine($"  Modified Tables: {diff.ModifiedTables.Count}");
            sb.AppendLine();

            foreach (var t in diff.AddedTables)
            {
                sb.AppendLine($"  [+] TABLE {t.TableName} ({t.Columns.Count} columns, {t.SourceRowCount} rows)");
                foreach (var c in t.Columns)
                    sb.AppendLine($"      + {c.Name} {c.DataType} (len={c.Length})");
            }

            foreach (var t in diff.RemovedTables)
            {
                sb.AppendLine($"  [-] TABLE {t.TableName} ({t.TargetRowCount} rows)");
            }

            foreach (var t in diff.ModifiedTables)
            {
                sb.AppendLine($"  [~] TABLE {t.TableName}");
                foreach (var c in t.AddedColumns)
                    sb.AppendLine($"      + Column {c.ColumnName} ({c.NewDataType}, len={c.NewLength})");
                foreach (var c in t.RemovedColumns)
                    sb.AppendLine($"      - Column {c.ColumnName} ({c.OldDataType}, len={c.OldLength})");
                foreach (var c in t.ModifiedColumns)
                    sb.AppendLine($"      ~ Column {c.ColumnName}: {c.OldDataType}(len={c.OldLength}) → {c.NewDataType}(len={c.NewLength})");
                if (t.RowCountDifference != 0)
                    sb.AppendLine($"      Δ Rows: {t.RowCountDifference:+0;-0} ({t.SourceRowCount} vs {t.TargetRowCount})");
            }

            return sb.ToString();
        }

        // ─────────────────────────────────────────────────────────────────────
        // SQL Dialect Helpers
        // ─────────────────────────────────────────────────────────────────────

        private static string Quote(string name, string dialect)
        {
            string safe = name.Replace("]", "").Replace("[", "").Replace("\"", "");
            return dialect switch
            {
                "pgsql" => $"\"{safe}\"",
                "mssql" => $"[{safe}]",
                _ => $"[{safe}]"  // ANSI / SQLite / Access style
            };
        }

        private static string PrimaryKeyAutoIncrement(string dialect)
        {
            return dialect switch
            {
                "pgsql" => " SERIAL PRIMARY KEY",
                "mssql" => " IDENTITY(1,1) PRIMARY KEY",
                "sqlite" => " INTEGER PRIMARY KEY AUTOINCREMENT",
                _ => " AUTOINCREMENT PRIMARY KEY"
            };
        }

        private static string MapDataType(JetDataType type, int length, string dialect)
        {
            return type switch
            {
                JetDataType.Boolean => dialect == "pgsql" ? "BOOLEAN" : "BIT",
                JetDataType.Byte => "TINYINT",
                JetDataType.Integer => "SMALLINT",
                JetDataType.LongInteger or JetDataType.Autonumber => dialect == "pgsql" ? "INTEGER" : "INT",
                JetDataType.Single => dialect == "pgsql" ? "REAL" : "FLOAT",
                JetDataType.Double => dialect == "pgsql" ? "DOUBLE PRECISION" : "DOUBLE",
                JetDataType.Currency => "DECIMAL(19,4)",
                JetDataType.DateTime => dialect == "pgsql" ? "TIMESTAMP" : "DATETIME",
                JetDataType.Memo => "TEXT",
                JetDataType.Text => length > 0 ? $"VARCHAR({length})" : "VARCHAR(255)",
                JetDataType.Binary => dialect == "pgsql" ? "BYTEA" : "VARBINARY(MAX)",
                JetDataType.Guid => dialect == "pgsql" ? "UUID" : "UNIQUEIDENTIFIER",
                _ => length > 0 ? $"VARCHAR({length})" : "VARCHAR(255)"
            };
        }

        private static void WriteTo(string path, StringBuilder sb)
        {
            string dir = Path.GetDirectoryName(Path.GetFullPath(path)) ?? ".";
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
        }
    }
}
