using System;
using System.IO;
using System.Text;
using AccessUtility.Models;

namespace AccessUtility.Exporters
{
    public static class SqlScriptExporter
    {
        public static string ExportDatabase(AccessDatabase db, string outputSqlPath)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"-- Access 97 Database SQL Export");
            sb.AppendLine($"-- Generated by AccessUtility (.NET 10 Native AOT)");
            sb.AppendLine($"-- Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            foreach (var table in db.Tables)
            {
                if (table.Columns.Count == 0) continue;

                string tableName = table.Name.Replace("'", "''");
                sb.AppendLine($"-- Table: {tableName}");
                sb.AppendLine($"DROP TABLE IF EXISTS [{tableName}];");
                sb.AppendLine($"CREATE TABLE [{tableName}] (");

                for (int i = 0; i < table.Columns.Count; i++)
                {
                    var col = table.Columns[i];
                    string colName = col.Name.Replace("]", "");
                    string dataTypeStr = MapSqlDataType(col.DataType);
                    string comma = i < table.Columns.Count - 1 ? "," : "";
                    sb.AppendLine($"    [{colName}] {dataTypeStr}{comma}");
                }
                sb.AppendLine(");");
                sb.AppendLine();

                // Inserts
                foreach (var row in table.Rows)
                {
                    var vals = new System.Collections.Generic.List<string>();
                    for (int i = 0; i < table.Columns.Count; i++)
                    {
                        var col = table.Columns[i];
                        row.TryGetValue(col.Name, out var val);
                        vals.Add(FormatSqlValue(val, col.DataType));
                    }
                    sb.AppendLine($"INSERT INTO [{tableName}] VALUES ({string.Join(", ", vals)});");
                }
                sb.AppendLine();
            }

            string dir = Path.GetDirectoryName(Path.GetFullPath(outputSqlPath)) ?? ".";
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(outputSqlPath, sb.ToString(), Encoding.UTF8);
            return outputSqlPath;
        }

        private static string MapSqlDataType(JetDataType type) => type switch
        {
            JetDataType.Boolean => "BOOLEAN",
            JetDataType.Byte => "TINYINT",
            JetDataType.Integer => "SMALLINT",
            JetDataType.LongInteger or JetDataType.Autonumber => "INT",
            JetDataType.Single => "FLOAT",
            JetDataType.Double => "DOUBLE",
            JetDataType.Currency => "DECIMAL(19,4)",
            JetDataType.DateTime => "DATETIME",
            JetDataType.Memo => "TEXT",
            _ => "VARCHAR(255)"
        };

        private static string FormatSqlValue(object? val, JetDataType type)
        {
            if (val == null || val == DBNull.Value) return "NULL";

            if (type == JetDataType.Boolean)
            {
                return Convert.ToBoolean(val) ? "1" : "0";
            }
            if (type is JetDataType.Integer or JetDataType.LongInteger or JetDataType.Byte or JetDataType.Autonumber)
            {
                return val.ToString() ?? "0";
            }
            if (type is JetDataType.Single or JetDataType.Double or JetDataType.Currency)
            {
                return val.ToString() ?? "0";
            }

            string str = val.ToString() ?? "";
            return $"'{str.Replace("'", "''")}'";
        }
    }
}
